id: A8F8790A4
title: Aspiration for Electric Lamps
type: translation
pechas:
- I1F7FFD1F
- I6A11E913
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:00.695989
  last_modified_at: 2023-01-04 12:45:00.696009
  collections:
  - Jigme Tenpé Wangchuk Series
  - Works of Tibetan Masters
alignment_to_base:
  I1F7FFD1F/E9B3: 66CB
  I6A11E913/799C: 66CB
